--- #YAML:1.0
name:                WebService-EveOnline
version:             0.61
abstract:            ~
license:             ~
author:              
    - Chris Carline <chris@carline.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    DBD::SQLite:                   0
    DBI:                           0
    LWP::UserAgent:                0
    Storable:                      0
    Test::More:                    0
    Time::Local:                   0
    XML::Simple:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
