# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WebService-EveOnline
version:      0.62
version_from: lib/WebService/EveOnline.pm
installdirs:  site
requires:
    DBD::SQLite:                   0
    DBI:                           0
    LWP::UserAgent:                0
    Storable:                      0
    Test::More:                    0
    Time::Local:                   0
    XML::Simple:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
