#!/usr/bin/perl

use strict;
use warnings;

use WebService::EveOnline;

my $API_KEY = $ENV{EVE_API_KEY};
my $USER_ID = $ENV{EVE_USER_ID};

my $eve = WebService::EveOnline->new( { user_id => $USER_ID, api_key => $API_KEY } );

foreach my $character ($eve->characters) {
    print $character->character_name . " has " . $character->account_balance . " ISK in the bank\n";
}
